# application.example.yml
# âš  ì´ íŒŒì¼ì€ ì˜ˆì‹œì…ë‹ˆë‹¤.
# 'application.yml'ë¡œ ì´ë¦„ì„ ë°”ê¾¸ê³ 
# í”„ë¡œì íŠ¸ì— ë§ê²Œ ê°’ì„ ì…ë ¥í•˜ì—¬ ì‚¬ìš©í•˜ì„¸ìš”.

# ì–´í”Œë¦¬ì¼€ì´ì…˜ ì´ë¦„ ì„¤ì •
spring:
  application:
    name: # ğŸ”§ í”„ë¡œì íŠ¸ì— ë§ê²Œ ë°˜ë“œì‹œ ìˆ˜ì •í•˜ì„¸ìš”.

  # íŒŒì¼ ì—…ë¡œë“œ ê´€ë ¨ ì„¤ì •
  servlet:
    multipart:
      max-file-size: 10MB  # ìµœëŒ€ íŒŒì¼ í¬ê¸°
      max-request-size: 30MB  # ìµœëŒ€ ìš”ì²­ í¬ê¸°

  jpa:
    open-in-view: false  # "Open EntityManager in View" ì„¤ì •
    show-sql: true  # JPA SQL ì¶œë ¥ ì—¬ë¶€
    hibernate:
      ddl-auto: none  # ğŸ”§ í”„ë¡œì íŠ¸ì— ë§ê²Œ ë°˜ë“œì‹œ ìˆ˜ì •í•˜ì„¸ìš”.
      format_sql: true  # Hibernate SQL í¬ë§· ì„¤ì • (ê°€ë…ì„±ì„ ìœ„í•´)
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl  # Hibernate ë¬¼ë¦¬ì  ë„¤ì´ë° ì „ëµ ì„¤ì •

  mvc:
    hiddenmethod:
      filter:
        enabled: true  # Hidden HTTP Methods ì‚¬ìš© ì—¬ë¶€ (HTML Formì—ì„œ PUT, DELETE ë“±ì„ ì‚¬ìš©í•˜ê¸° ìœ„í•¨)
    static-path-pattern: "/static/**"  # ì •ì  ìì› ê²½ë¡œ ì„¤ì •

  thymeleaf:
    cache: false  # Thymeleaf í…œí”Œë¦¿ ìºì‹œ ë¹„í™œì„±í™” (ê°œë°œ ì¤‘ ìºì‹œ ì‚¬ìš©ì„ í”¼í•˜ê¸° ìœ„í•¨)

  h2:
    console:
      enabled: false # H2 ì½˜ì†” í™œì„±í™” ğŸ”§ í”„ë¡œì íŠ¸ì— ë§ê²Œ ë°˜ë“œì‹œ ìˆ˜ì •í•˜ì„¸ìš”.

  messages:
    basename: classpath:messages  # ë©”ì‹œì§€ ë¦¬ì†ŒìŠ¤ ë²ˆë“¤ ì„¤ì •

  config:
    import: optional:classpath:application-secret.yml # secret í”„ë¡œíŒŒì¼ì„ ì„¤ì •ì— ë³‘í•©

  profiles:
    #active: dev  # ğŸ”§ í”„ë¡œì íŠ¸ì— ë§ê²Œ ë°˜ë“œì‹œ ìˆ˜ì •í•˜ì„¸ìš”.

# Hibernate SQL ë¡œê·¸ ì¶œë ¥
logging:
  level:
    org:
      springframework:
        web: DEBUG
        web.servlet.DispatcherServlet: DEBUG
        security: DEBUG
        beans: DEBUG
        jdbc.core.JdbcTemplate: DEBUG
        transaction: DEBUG
      hibernate:
        SQL: DEBUG
        type.descriptor.sql.BasicBinder: TRACE
      apache:
        coyote.http11: WARN
        tomcat.util.net: WARN

# ìš´ì˜ í™˜ê²½ì—ì„œëŠ” ë¡œê·¸ë¥¼ ì¤„ì—¬ì„œ ì„¤ì •
# spring:
#   profiles:
#     active: prod
#
# logging:
#   level:
#     org:
#       springframework:
#         web: INFO
#         web.servlet.DispatcherServlet: INFO
#         security: WARN
#         beans: INFO
#         jdbc.core.JdbcTemplate: WARN
#         transaction: WARN
#       hibernate:
#         SQL: WARN
#       apache:
#         coyote.http11: ERROR
#         tomcat.util.net: ERROR


# Actuator ì„¤ì •
management:
  metrics:
    profiler:
      enabled: true  # ë©”íŠ¸ë¦­ í”„ë¡œíŒŒì¼ëŸ¬ í™œì„±í™”
  endpoints:
    web:
      exposure:
        include: "*"  # Actuator ì—”ë“œí¬ì¸íŠ¸ ë…¸ì¶œ ì„¤ì •
      base-path: "/actuator/profiler"  # Actuator ì—”ë“œí¬ì¸íŠ¸ ê¸°ë³¸ ê²½ë¡œ ì„¤ì •

# Tomcat ìƒëŒ€ì  ë¦¬ë‹¤ì´ë ‰íŠ¸ ì‚¬ìš©
server:
  tomcat:
    use-relative-redirects: true

  # Whitelabel ì—ëŸ¬ í˜ì´ì§€ ë¹„í™œì„±í™”
  error:
    whitelabel:
      enabled: false

  servlet:
    session:
      cookie:
        http-only: false  # HTTP-Only ì¿ í‚¤ ì„¤ì •

mediatype:
  json: "application/json;charset=UTF-8"
